# https://finviz.com/help/screener.ashx Filters explanations can also be found here

from enum import Enum


class FilterCodes(str, Enum):
    # CUSTOM FILTERS
    MARKET_CAP = "cap_to"
    PRICE_EARNINGS = "fa_pe_to"
    FORWARD_P_E = "fa_fpe_to"
    PRICE_EARNINGS_GROWTH = "fa_peg_to"
    PRICE_SALES = "fa_ps_to"
    PRICE_BOOK = "fa_pb_to"
    PRICE_CASH = "fa_pc_to"
    PRICE_FREE_CASH_FLOW = "fa_pfcf_to"
    EPS_GROWTH_THIS_YEAR = "fa_epsyoy_to"
    EPS_GROWTH_NEXT_YEAR = "fa_epsyoy1_to"
    EPS_GROWTH_PAST_FIVE_YEARS = "fa_eps5years_to"
    EPS_GROWTH_NEXT_FIVE_YEARS = "fa_estltgrowth_to"
    SALES_GROWTH_NEXT_FIVE_YEARS = "fa_sales5years_to"
    EPS_GROWTH_QTR_OVER_QTR = "fa_epsqoq_to"
    SALES_GROWTH_QTR_OVER_QTR = "fa_salesqoq_to"
    DIVIDEND_YIELD = "fa_div_to"
    RETURN_ON_ASSETS = "fa_roa_to"
    RETURN_ON_EQUITY = "fa_roe_to"
    RETURN_ON_INVESTMENT = "fa_roi_to"
    CURRENT_RATIO = "fa_curratio_to"
    QUICK_RATIO = "fa_quickratio_to"
    LT_DEBT_EQUITY = "fa_ltdebteq_to"
    DEBT_EQUITY = "fa_debteq_to"
    GROSS_MARGIN = "fa_grossmargin_to"
    OPERATING_MARGIN = "fa_opermargin_to"
    NET_PROFIT_MARGIN = "fa_netmargin_to"
    PAYOUT_RATIO = "fa_payoutratio_to"
    INSIDER_OWNERSHIP = "sh_insiderown_to"
    INSIDER_TRANSACTIOONS = "sh_insidertransac_to"
    INSTITUTIONAL_OWNERSHIP = "sh_instown_to"
    INSTITUTIONAL_TRANSACTIONS = "sh_insttrans_to"
    FLOAT_SHORT = "sh_short_to"
    EARNINGS_DATE = "earningsdate_x"
    RSI_14 = "ta_rsi_to"
    GAP = "ta_gap_to"
    CHANGE = "ta_change_to"
    CHANGE_FROM_OPEN = "ta_changeopen_to"
    BETA = "ta_beta_to"
    ATR = "ta_averagetruerange_to"
    AVERAGE_VOLUME = "sh_avgvol_to"
    RELATIVE_VOLUME = "sh_relvol_to"
    CURRENT_VOLUME = "sh_curvol_to"
    PRICE = "sh_price_to"
    SHARES_OUTSTANDING = "sh_outstanding_to"
    AFTER_HOURS_CLOSE = "ah_close_to"
    AFTER_HOURS_CHANGE = "ah_change_to"

    PERFORMANCE_DAY = "ta_perf_to-d"
    PERFORMANCE_WEEK = "ta_perf_to-1w"
    PERFORMANCE_MONTH = "ta_perf_to-4w"
    PERFORMANCE_QUARTER = "ta_perf_to-13w"
    PERFORMANCE_HALF = "ta_perf_to-26w"
    PERFORMANCE_YTD = "ta_perf_to-ytd"

    PRICE_ABOVE_SMA_20 = "ta_sma20_to-a"
    PRICE_ABOVE_SMA_50 = "ta_sma50_to-a"
    PRICE_ABOVE_SMA_200 = "ta_sma200_to-a"

    PRICE_BELOW_SMA_20 = "ta_sma20_to-b"
    PRICE_BELOW_SMA_50 = "ta_sma50_to-b"
    PRICE_BELOW_SMA_200 = "ta_sma200_to-b"

    # BASE FILTERS

    # SIGNALS
    TOP_GAINERS = "ta_topgainers"
    TOP_LOSERS = "ta_toplosers"
    NEW_HIGH = "ta_newhigh"
    NEW_LOW = "ta_newlow"
    MOST_VOLATILE = "ta_mostvolatile"
    MOST_ACTIVE = "ta_mostactive"
    UNUSUAL_VOLUME = "ta_unusualvolume"
    OVERBOUGHT = "ta_overbought"
    OVERSOLD = "ta_oversold"
    DOWNGRADES = "n_downgrades"
    UPGRADES = "n_upgrades"
    EARNINGS_BEFORE = "n_earningsbefore"
    EARNINGS_AFTER = "n_earningsafter"
    RECENT_INSIDER_BUYING = "it_latestbuys"
    RECENT_INSIDER_SELLING = "it_latestsales"
    MAJOR_NEWS = "n_majornews"
    HPROZONTAL_SR = "ta_p_horizontal"
    TL_RESISTANCE = "ta_p_tl_resistance"
    TL_SUPPORT = "ta_p_tl_support"
    WEDGE = "ta_p_wedge"
    TRIANGLE_ASCENDING = "ta_p_triangleascending"
    TRIANGLE_DESCENDING = "ta_p_triangledescending"
    CHANNEL_UP = "ta_p_channelup"
    CHANNEL_DOWN = "ta_p_channeldown"
    CHANNEL = "ta_p_channel"
    DOUBLE_TOP = "ta_p_doubletop"
    DOUBLE_BOTTOM = "ta_p_doublebottom"
    MULTIPLE_TOP = "ta_p_multipletop"
    MULTIPLE_BOTTOM = "ta_p_multiplebottom"
    HEAD_SHOULDERS = "ta_p_headandshoulders"
    HEAD_SHOULDERS_INVERSE = "ta_p_headandshouldersinv"

    # ANALYST RECOMMENDATION
    ANALYST_STRONG_BUY = "an_recom_strongbuy"
    ANALYST_BUY_BETTER = "an_recom_buybetter"
    ANALYST_BUY = "an_recom_buy"
    ANALYST_HOLD_BETTER = "an_recom_holdbetter"
    ANALYST_HOLD = "an_recom_hold"
    ANALYST_HOLD_WORSE = "an_recom_holdworse"
    ANALYST_SELL = "an_recom_sell"
    ANALYST_SELL_WORSE = "an_recom_sellworse"
    ANALYST_STRONG_SELL = "an_recom_strongsell"

    # EARNINGS DATES
    EARNINGS_TODAY = "earningsdate_today"
    EARNINGS_TODAY_BEFORE = "earningsdate_todaybefore"
    EARNINGS_TODAY_AFTER = "earningsdate_todayafter"
    EARNINGS_TOMORROW = "earningsdate_tomorrow"
    EARNINGS_TOMORROW_BEFORE = "earningsdate_tomorrowbefore"
    EARNINGS_TOMORROW_AFTER = "earningsdate_tomorrowafter"
    EARNINGS_YESTERDAY = "earningsdate_yesterday"
    EARNINGS_YESTERDAY_BEFORE = "earningsdate_yesterdaybefore"
    EARNINGS_YESTERDAY_AFTER = "earningsdate_yesterdayafter"
    EARNINGS_NEXT_DAYS_5 = "earningsdate_nextdays5"
    EARNINGS_PREV_DAYS_5 = "earningsdate_prevdays5"
    EARNINGS_THIS_WEEK = "earningsdate_thisweek"
    EARNINGS_NEXT_WEEK = "earningsdate_nextweek"
    EARNINGS_PREV_WEEK = "earningsdate_prevweek"
    EARNINGS_THIS_MONTH = "earningsdate_thismonth"

    # OPTIONABLE / SHORTABLE AND INVERSE
    OPTIONABLE = "sh_opt_option"
    SHORTABLE = "sh_opt_short"
    NOT_OPTIONABLE = "sh_opt_notoption"
    NOT_SHORTABLE = "sh_opt_notshort"
    OPTIONABLE_SHORTABLE = "sh_opt_optionshort"
    OPTIONABLE_NOT_SHORTABLE = "sh_opt_optionnotshort"
    SHORTABLE_NOT_OPTIONABLE = "sh_opt_notoptionshort"
    NOT_OPTIONABLE_SHORTABLE = "sh_opt_notoptionnotshort"
